### ISSUE TITLE
dict plugin crashes if directory does not exist

### ISSUE THREAD

**Issue by DaveDavenport** [marvinkreis/rofi-plugins#2]
```
[dict] Could not open directory: /home/mkoedam/.local/share/dicts/json
Segmentation fault (core dumped)
```

backtrace:
```
#0  0x00007f34720200a9 in __readdir (dirp=0x0) at ../sysdeps/posix/readdir.c:44
#1  0x00007f346a0fd2b2 in set_dict_files (dir_name=0x557c6a3fae40 "/home/mkoedam/.local/share/dicts/json", sw=<optimized out>) at src/dict.c:410
#2  0x00007f346a0fd841 in dict_init (sw=0x7f346a2ff120 <mode>) at src/dict.c:234
#3  0x0000557c698cc2fd in run_switcher (mode=2) at ../source/rofi.c:170
#4  0x0000557c698ccc17 in startup (data=<optimized out>) at ../source/rofi.c:702
#5  0x00007f34745fae25 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007f34745fb1f0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007f34745fb502 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x0000557c698c301c in main (argc=<optimized out>, argv=<optimized out>) at ../source/rofi.c:982
```

**Comment by marvinkreis** [comment]
Should be fixed now, thanks for the feedback.
